### ISSUE TITLE
Cannot find include_lib

### ISSUE THREAD

**Issue by garrensmith** [yuce/erlang-vscode#13]
Hi, 

I really like this plugin. Thanks for your hard work on it. I have one issue, if I import a header file like this:

`-include_lib("fabric/src/fabric2.hrl")`
Notice, that its in the src folder. Then I get this error:

`can't find include lib "fabric/src/fabric2.hrl"`

Is there a way I can fix this?

**Comment by yuce** [comment]
Hi, I guess you are using the more popular and more featureful vscode_erlang plugin: https://github.com/pgourlain/vscode_erlang

**Comment by garrensmith** [comment]
You right. Apologies.
