### ISSUE TITLE
Syntax highlight - issue

### ISSUE THREAD

**Issue by qisoster** [yuce/erlang-vscode#6]
Hi. The following code compiles without errors but syntax highlight has issues on line 13.
Code below:
```
start_server() ->
    register(chat_server, spawn(fun() ->
            process_flag(trap_exit, true),
            Val = (catch server_loop([])),
            io:format("Server terminated with:~p.~n", [Val])
        end)).
```

![erl_syntax](https://cloud.githubusercontent.com/assets/19863674/20226003/364f0fd0-a814-11e6-8538-0e448b0cad19.png)

**Comment by yuce** [comment]
It works with the theme I'm using: https://marketplace.visualstudio.com/items?itemName=gerane.Theme-Twilight Can you try to use a different theme ?

![screen shot](https://cloud.githubusercontent.com/assets/513114/20242987/747d1680-a954-11e6-9cd6-e9f6973d2240.png)

**Comment by qisoster** [comment]
Indeed. I tried a different theme and it looks correct.
